services:
  mysql:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: powerdns
      MYSQL_USER: powerdns
      MYSQL_PASSWORD: secret
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-psecret", "-e", "SELECT 1;"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  pdns:
    image: powerdns/pdns-auth-50
    command:
      - "--api"
      - "--api-key=secret"
      - "--webserver"
      - "--webserver-address=0.0.0.0"
      - "--webserver-allow-from=0.0.0.0/0"
      - "--loglevel=6"
      - "--disable-syslog=yes"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASS=secret
      - MYSQL_DB=powerdns
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api", "-H", "X-API-Key: secret"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped

  recursor:
    image: powerdns/pdns-recursor-53
    command:
      - --webserver=yes
      - --webserver-address=0.0.0.0
      - --webserver-port=8082
      - --webserver-allow-from=0.0.0.0/0
      - --api-key=secret
      - --loglevel=6
      - --disable-syslog=yes
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/api", "-H", "X-API-Key: secret"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped

