ARG RECURSOR_VERSION=54
FROM powerdns/pdns-recursor-${RECURSOR_VERSION}:latest

USER root

RUN mkdir /etc/powerdns/api.d/ && \
  chown pdns:pdns /etc/powerdns/api.d/ && \
  chmod 755 /etc/powerdns/api.d/

USER pdns
