package powerdns

import (
	"context"
	"io"
	"net/http"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestListTSIGKeys(t *testing.T) {
	client := newTestClient(func(r *http.Request) (*http.Response, error) {
		assert.Equal(t, http.MethodGet, r.Method)
		assert.Equal(t, "/api/v1/servers/localhost/tsigkeys", r.URL.Path)
		// The API omits the secret when listing.
		return jsonResponse(http.StatusOK, `[{"id":"test.","name":"test","algorithm":"hmac-sha256","key":"","type":"TSIGKey"}]`), nil
	})

	keys, err := client.ListTSIGKeys(context.Background())
	if !assert.NoError(t, err) {
		return
	}

	if !assert.Len(t, keys, 1) {
		return
	}
	assert.Equal(t, "test.", keys[0].ID)
	assert.Equal(t, "hmac-sha256", keys[0].Algorithm)
	assert.Empty(t, keys[0].Key)
}

func TestGetTSIGKey(t *testing.T) {
	client := newTestClient(func(r *http.Request) (*http.Response, error) {
		assert.Equal(t, http.MethodGet, r.Method)
		assert.Equal(t, "/api/v1/servers/localhost/tsigkeys/test.", r.URL.Path)
		return jsonResponse(http.StatusOK, `{"id":"test.","name":"test","algorithm":"hmac-sha256","key":"c2VjcmV0","type":"TSIGKey"}`), nil
	})

	key, err := client.GetTSIGKey(context.Background(), "test.")
	if !assert.NoError(t, err) {
		return
	}

	assert.Equal(t, "test.", key.ID)
	assert.Equal(t, "test", key.Name)
	assert.Equal(t, "c2VjcmV0", key.Key)
}

func TestGetTSIGKeyNotFound(t *testing.T) {
	client := newTestClient(func(r *http.Request) (*http.Response, error) {
		return jsonResponse(http.StatusNotFound, `{"error":"Not Found"}`), nil
	})

	key, err := client.GetTSIGKey(context.Background(), "missing.")
	assert.Nil(t, key)
	assert.ErrorIs(t, err, ErrNotFound)
}

func TestCreateTSIGKey(t *testing.T) {
	client := newTestClient(func(r *http.Request) (*http.Response, error) {
		assert.Equal(t, http.MethodPost, r.Method)
		assert.Equal(t, "/api/v1/servers/localhost/tsigkeys", r.URL.Path)
		return jsonResponse(http.StatusCreated, `{"id":"test.","name":"test","algorithm":"hmac-sha256","key":"Z2VuZXJhdGVk","type":"TSIGKey"}`), nil
	})

	created, err := client.CreateTSIGKey(context.Background(), TSIGKey{Name: "test", Algorithm: "hmac-sha256"})
	if !assert.NoError(t, err) {
		return
	}

	assert.Equal(t, "test.", created.ID)
	// An omitted secret comes back generated by the server.
	assert.Equal(t, "Z2VuZXJhdGVk", created.Key)
}

func TestUpdateTSIGKeyOmitsAlgorithm(t *testing.T) {
	client := newTestClient(func(r *http.Request) (*http.Response, error) {
		assert.Equal(t, http.MethodPut, r.Method)
		assert.Equal(t, "/api/v1/servers/localhost/tsigkeys/test.", r.URL.Path)

		raw, err := io.ReadAll(r.Body)
		if !assert.NoError(t, err) {
			return nil, err
		}
		defer func() {
			assert.NoError(t, r.Body.Close())
		}()
		body := string(raw)
		// Sending an algorithm here would make PowerDNS store a second key
		// under the same name, so it must never appear in the payload.
		assert.NotContains(t, body, "algorithm")
		return jsonResponse(http.StatusOK, `{"id":"renamed.","name":"renamed","algorithm":"hmac-sha256","key":"c2VjcmV0","type":"TSIGKey"}`), nil
	})

	updated, err := client.UpdateTSIGKey(context.Background(), "test.", TSIGKey{Name: "renamed", Key: "c2VjcmV0"})
	if !assert.NoError(t, err) {
		return
	}

	assert.Equal(t, "renamed.", updated.ID)
}

func TestDeleteTSIGKey(t *testing.T) {
	client := newTestClient(func(r *http.Request) (*http.Response, error) {
		assert.Equal(t, http.MethodDelete, r.Method)
		assert.Equal(t, "/api/v1/servers/localhost/tsigkeys/test.", r.URL.Path)
		return jsonResponse(http.StatusNoContent, ``), nil
	})

	assert.NoError(t, client.DeleteTSIGKey(context.Background(), "test."))
}
